"""Generate compact MoonBit strings from the vendored, licensed TeX data."""
from pathlib import Path
import hashlib
import re
ROOT = Path(__file__).resolve().parent.parent
source = ROOT / 'testdata/hyphen/hyph-en-us.tex'
text = re.sub(r'%[^\n]*', '', source.read_text())
patterns = ' '.join(re.search(r'\\patterns\s*\{([^}]+)\}', text).group(1).split())
exceptions = ' '.join(re.search(r'\\hyphenation\s*\{([^}]+)\}', text).group(1).split())
header = '''// Generated by scripts/generate_hyphen.py. Do not edit.
// Copyright (C) 1990, 2004, 2005 Gerard D.C. Kuiken
// Copying and distribution of this file, with or without modification,
// are permitted in any medium without royalty provided the copyright
// notice and this notice are preserved.
'''
(ROOT / 'hyphen/english.mbt').write_text(header + '\n///|\nlet english_patterns : String = "' + patterns + '"\n\n///|\nlet english_exceptions : String = "' + exceptions + '"\n', encoding='utf-8')
(ROOT / 'testdata/hyphen/SHA256SUMS').write_text(hashlib.sha256(source.read_bytes()).hexdigest() + '  hyph-en-us.tex\n')
print(len(patterns.split()), 'patterns,', len(exceptions.split()), 'exceptions')
